kind: pipeline
type: exec
name: default

platform:
  os: linux

environment:
  product: "serversuite"

steps:
- name: Sync Files (Main)
  commands:
  - cd /home/t320569/github
  - echo $product
  - if [ -d "$product" ]; then git --git-dir="/home/t320569/github/${product}/.git" pull; else git clone "https://github.com/wessenstam/${product}/"; fi
  - chown -R t320569:t320569 "/home/t320569/github/$product"  
  when:
    branch:
    - main
  
- name: Build Dev HTML(dev)
  commands:
  - echo $product
  - docker run --rm --name build_dev_html -v "/home/t320569/github/${product}":/web wessenstam/sphinx_server:2.2 /usr/bin/sphinx-build -a . dev
  - chown -R t320569:t320569 "/home/t320569/github/${product}/dev"  
  when:
    branch:
    - dev