kind: pipeline
type: exec
name: default

steps:
- name: Sync Files (Main)
  commands:
  - cd /home/ubuntu/github
  - if [ -d "$PRODUCT_NAME" ]; then git --git-dir=/home/ubuntu/github/$PRODUCT_NAME/.git pull; else git clone "https://github.com/wessenstam/$PRODUCT_NAME/"; fi
  - chown -R ubuntu:ubuntu "/home/ubuntu/github/$PRODUCT_NAME"  
  environment:
    PRODUCT_NAME: serversuite
  when:
    branch:
    - main
  
- name: Build Dev HTML(dev)
  commands:
  - git clone --branch dev "https://github.com/wessenstam/$PRODUCT_NAME/" /tmp/$PRODUCT_NAME
  - docker run --rm --name build_dev_html -v /var/www/html:/develop -v /tmp/$PRODUCT_NAME:/web wessenstam/sphinx_server:2.2 /usr/bin/sphinx-build -a . /develop/$PRODUCT_NAME/dev
  - rm -Rf /tmp/$PRODUCT_NAME
  environment:
    PRODUCT_NAME: serversuite
  when:
    branch:
    - dev 