kind: pipeline
type: exec
name: default

steps:
- name: Sync Files (Main)
  commands:
  - git clone --branch main "https://github.com/wessenstam/$PRODUCT_NAME/" /tmp/$DRONE_COMMIT_SHA
  - docker run --rm --name build_dev_html -v /home/ubuntu/www/html/:/develop -v /tmp/$DRONE_COMMIT_SHA:/web wessenstam/sphinx_server:2.2 /usr/bin/sphinx-build -a . /develop/$PRODUCT_NAME/dev
  - chown -Rf ubuntu:ubuntu /home/ubuntu/www/html/$PRODUCT_NAME
  - rm -Rf /tmp/$DRONE_COMMIT_SHA
  environment:
    PRODUCT_NAME: serversuite
  when:
    branch:
    - main
  
- name: Build Dev HTML(dev)
  commands:
  - git clone --branch dev "https://github.com/wessenstam/$PRODUCT_NAME/" /tmp/$PRODUCT_NAME
  - docker run --rm --name build_dev_html -v /var/www/html:/develop -v /tmp/$PRODUCT_NAME:/web wessenstam/sphinx_server:2.2 /usr/bin/sphinx-build -a . /develop/$PRODUCT_NAME/dev
  - rm -Rf /tmp/$PRODUCT_NAME
  environment:
    PRODUCT_NAME: serversuite
  when:
    branch:
    - dev 