kind: pipeline
type: exec
name: default

platform:
  os: linux
  
steps:
- name: Sync Files (Main)
  commands:
  - cd /home/t320569/github
  - if [ -d "serversuite" ]; then git --git-dir=/home/t320569/github/serversuite/.git pull; else git clone https://github.com/wessenstam/serversuite/; fi
  - chown -R t320569:t320569 /home/t320569/github/serversuite  
  when:
    branch:
    - main